ALTER TABLE `specializations` CHANGE `en` `en` VARCHAR(50) CHARSET utf8 NULL; 
ALTER TABLE `trainings` CHANGE `en` `en` VARCHAR(50) CHARSET utf8 NULL; 
ALTER TABLE `faculties` CHANGE `en` `en` VARCHAR(50) CHARSET utf8 NULL; 
ALTER TABLE `modules` CHANGE `en` `en` VARCHAR(50) CHARSET utf8 NULL; 